/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\hires\configurator_scene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/configurator_scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.375, 0, -1.286]} rotation={[Math.PI, -1.027, Math.PI]} scale={0.557}>
        <mesh geometry={nodes.pot.geometry} material={materials.pot} />
        <mesh geometry={nodes.pot_1.geometry} material={materials.GROUND} />
        <group position={[-0.167, 2.19, 0.052]}>
          <mesh geometry={nodes['3DGeom~8_Defintion'].geometry} material={materials['leaf.001']} />
          <mesh geometry={nodes['3DGeom~8_Defintion_1'].geometry} material={materials['trunk.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <group position={[0.017, 1.281, 4.203]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={-21.219}>
        <mesh geometry={nodes.path1_1.geometry} material={materials['SVGMat.010']} />
        <mesh geometry={nodes.path1_2.geometry} material={materials['SVGMat.011']} />
        <mesh geometry={nodes.path1_3.geometry} material={materials['SVGMat.012']} />
        <mesh geometry={nodes.path1_4.geometry} material={materials['SVGMat.013']} />
        <mesh geometry={nodes.path1_5.geometry} material={materials['SVGMat.014']} />
        <mesh geometry={nodes.path1_6.geometry} material={materials['SVGMat.015']} />
        <mesh geometry={nodes.path1_7.geometry} material={materials['SVGMat.016']} />
        <mesh geometry={nodes.path1_8.geometry} material={materials['SVGMat.017']} />
        <mesh geometry={nodes.path1_9.geometry} material={materials['SVGMat.018']} />
        <mesh geometry={nodes.path1_10.geometry} material={materials['SVGMat.019']} />
        <mesh geometry={nodes.path1_11.geometry} material={materials['SVGMat.020']} />
        <mesh geometry={nodes.path1_12.geometry} material={materials['SVGMat.021']} />
        <mesh geometry={nodes.path1_13.geometry} material={materials['SVGMat.022']} />
        <mesh geometry={nodes.path1_14.geometry} material={materials['SVGMat.023']} />
      </group>
      <group position={[0.375, 0.172, 2.9]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['oak veneer']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['fabric sofa']} />
      </group>
    </group>
  )
}

useGLTF.preload('/configurator_scene.glb')
