/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\cop.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cop.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.STOP002.geometry} material={materials['Transparent plastic']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes.G002.geometry} material={materials['Button Light']} position={[-0.938, 1.113, -0.014]} scale={0.944} />
      <mesh geometry={nodes.Braille_Stop002.geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes.Braille_G002.geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes.Braille_Bell002.geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes.Braille_1002.geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes.Bell002.geometry} material={materials['Button Light Yellow']} position={[-0.938, 1.113, -0.014]} scale={0.944} />
      <mesh geometry={nodes['ALFT-010-104_COP_LED_Strip-2006'].geometry} material={materials.BlueHaloLight} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes['ALFT-010-104_COP_LED_Strip-1006'].geometry} material={materials.BlueHaloLight} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <group position={[-0.938, 1.114, -0.014]} scale={0.944}>
        <mesh geometry={nodes.Mesh_50007.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Mesh_50007_1.geometry} material={materials.RedLight} />
      </group>
      <mesh geometry={nodes['ALFT-010-102_COP_Part_C-2006'].geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes['ALFT-010-102_COP_Part_C-1006'].geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <mesh geometry={nodes['ALFT-010-101_COP_Part_B-1006'].geometry} material={materials['Metal.001']} position={[-0.938, 1.114, -0.014]} scale={0.944} />
      <group position={[-0.938, 1.114, -0.014]} scale={0.944}>
        <mesh geometry={nodes.Mesh_54019.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Mesh_54019_1.geometry} material={materials['Button Light']} />
      </group>
      <group position={[-0.938, 1.114, -0.014]} scale={0.944}>
        <mesh geometry={nodes.Mesh_54018.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Mesh_54018_1.geometry} material={materials['Button Light']} />
      </group>
      <group position={[-0.938, 1.114, -0.014]} scale={0.944}>
        <mesh geometry={nodes.Mesh_54017.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Mesh_54017_1.geometry} material={materials['Transparent plastic']} />
      </group>
      <group position={[-0.938, 1.114, -0.014]} scale={0.944}>
        <mesh geometry={nodes.Mesh_54016.geometry} material={materials['Metal.001']} />
        <mesh geometry={nodes.Mesh_54016_1.geometry} material={materials['Button Light']} />
      </group>
      <mesh geometry={nodes['1002'].geometry} material={materials['Button Light']} position={[-0.938, 1.113, -0.014]} scale={0.944} />
    </group>
  )
}

useGLTF.preload('/cop.glb')
