/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\orion_door.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/orion_door.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DOOR_FRAME_UPRIGHTstp-1'].geometry} material={materials['Stainless Steel']} position={[-0.218, 0.001, -0.691]} />
      <mesh geometry={nodes['DOOR_FRAME_UPRIGHTstp-2'].geometry} material={materials['Stainless Steel']} position={[-0.218, 0.001, -0.691]} />
      <mesh geometry={nodes['DOOR_SILL_PROFILE_UPDATEDstp-1'].geometry} material={materials['Stainless Steel']} position={[-0.218, 0.001, -0.691]} />
      <mesh geometry={nodes['DOORstp-1'].geometry} material={materials['Stainless Steel']} position={[-0.218, 0.001, -0.69]} />
      <mesh geometry={nodes['DOORstp-2'].geometry} material={materials['Stainless Steel']} position={[-0.216, 0, -0.69]} />
      <mesh geometry={nodes['DOORstp-3'].geometry} material={materials['Stainless Steel']} position={[-0.216, 0, -0.694]} />
      <mesh geometry={nodes['DOORstp-4'].geometry} material={materials['Stainless Steel']} position={[-0.218, 0.001, -0.695]} />
      <group position={[-0.067, 0.979, -0.507]} rotation={[-0.754, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_21002.geometry} material={materials['color-1.002']} />
        <mesh geometry={nodes.Mesh_21002_1.geometry} material={materials['color.002']} />
      </group>
      <group position={[-0.075, 0.962, -0.507]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_18003.geometry} material={materials['color.003']} />
        <mesh geometry={nodes.Mesh_18003_1.geometry} material={materials['Editable Brushed  Aluminium.001']} />
      </group>
      <group position={[-0.067, 1.007, -0.507]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_19002.geometry} material={materials['Editable Brushed  Aluminium.001']} />
        <mesh geometry={nodes.Mesh_19002_1.geometry} material={materials['color-2.001']} />
        <mesh geometry={nodes.Mesh_19002_2.geometry} material={materials['color-3.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/orion_door.glb')
