/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\phoenix_door.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/phoenix_door.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Aussie_Lifts_Door_Handle-1001'].geometry} material={materials['Editable Brushed  Aluminium.001']} position={[-0.038, 0.983, -0.444]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[-0.022, 0.988, -0.528]} rotation={[-0.754, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_21001.geometry} material={materials['color-1.002']} />
        <mesh geometry={nodes.Mesh_21001_1.geometry} material={materials['color.002']} />
      </group>
      <group position={[-0.03, 0.97, -0.528]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_18001.geometry} material={materials['color.003']} />
        <mesh geometry={nodes.Mesh_18001_1.geometry} material={materials['Editable Brushed  Aluminium.001']} />
      </group>
      <group position={[-0.022, 1.016, -0.528]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh_19001.geometry} material={materials['Editable Brushed  Aluminium.001']} />
        <mesh geometry={nodes.Mesh_19001_1.geometry} material={materials['color-2.001']} />
        <mesh geometry={nodes.Mesh_19001_2.geometry} material={materials['color-3.001']} />
      </group>
      <mesh geometry={nodes['GEN_3_1850_DOOR_D02-1001'].geometry} material={materials['MetalFrame.001']} position={[-0.075, 0.958, 0.44]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes['GEN_3_1850_DOOR_D03-1001'].geometry} material={materials['MetalFrame.001']} position={[-0.07, 0.026, -0.003]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes['GEN_3_1850_DOOR_D04-1003'].geometry} material={materials['Procedural Frosted Glass']} position={[-0.072, 0.958, -0.003]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes['GEN_3_1850_DOOR_P03-1001'].geometry} material={materials['MetalFrame.001']} position={[-0.077, 1.006, -0.578]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes['GEN_3_1850_DOOR_P04-1001'].geometry} material={materials['Editable Brushed  Aluminium.001']} position={[-0.077, 0.001, -0.003]} rotation={[0, 1.571, 0]} />
    </group>
  )
}

useGLTF.preload('/phoenix_door.glb')
